spring:
  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 600000
  
  # Redis Configuration (Prod)
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  # Disable Docker Compose support in Prod
  docker:
    compose:
      enabled: false
      
  # Prod JPA settings
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

# Application Config (Prod)
app:
  base-url: ${APP_BASE_URL}

# Logging configuration
logging:
  level:
    root: INFO
    com.next.nexrailai: INFO
