spring:
  # Database configuration (Local Docker)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/NexRailAI
    username: ${DEV_DB_USER_NAME} # Local DB User
    password: ${DEV_DB_USER_PASSWORD} # Local DB Password
  # Docker Compose (Auto-start for Dev)
  docker:
    compose:
      enabled: true
      file: compose.yaml
  
  # Dev-specific logging
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Application Config (Dev)
app:
  base-url: https://23be455b01ec.ngrok-free.app

# Logging configuration
level:
  root: INFO
  com.next.nexrailai: DEBUG